### ISSUE TITLE
COCO上训练号的模型

### ISSUE THREAD

**Issue by zhu2014yi** [VDIGPKU/CBNet_caffe#21]
请问是否打算分享COCO上训练好的模型？

**Comment by PKUbahuangliuhe** [comment]
we will release code and some model based on mmdetection soon发自我的iPhone------------------ 原始邮件 ------------------发件人: zhu2014yi  <notifications@github.com>发送时间: 2020年4月7日 12:56收件人: PKUbahuangliuhe/CBNet <CBNet@noreply.github.com>抄送: Subscribed <subscribed@noreply.github.com>主题: 回复：[PKUbahuangliuhe/CBNet] COCO上训练号的模型 (#21)
请问是否打算分享COCO上训练好的模型？

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/PKUbahuangliuhe/CBNet/issues/21",
"url": "https://github.com/PKUbahuangliuhe/CBNet/issues/21",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by zhu2014yi** [comment]
thanks

在 2020年4月7日星期二，Yudong Liu <notifications@github.com> 写道：
